version: '3'

services:
  le-qcm:
    container_name: le-qcm
    build:
      context: ./
      dockerfile: Dockerfile.prod
      args:
        DATABASE_URL: ${DATABASE_URL}
        NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
        CLERK_SECRET_KEY: ${CLERK_SECRET_KEY}
        CLERK_TRUST_HOST: ${CLERK_TRUST_HOST}
    restart: always
    ports:
      - 3000:3000

  # Add more containers below (nginx, postgres, etc.)